version: '3'
services:
  nodejs:
    image: node_consulta_credito
    restart: always
    build: .
    ports:
      - "9090:5678"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - /opt/docker_volumes/db_consulta_credito:/var/lib/postgresql/data
#      - ./docker-compose-initdb.sql:/docker-entrypoint-initdb.d/docker-compose-initdb.sql
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_PASSWORD=123456